export default function () {
  return {
    allEmployees: [],
    myEmployee: {},
    currentEmployee: {},
    departments: [],
    currentDepartment: {},
    designations: [],
    currentDesignation: {},
    leaves: [],
    leaveApprovals: [],
    myLeaves: [],
    currentLeave: {},
    leaveTypes: [],
    currentLeaveType: {},
    overtimes: [],
    overtimeApprovals: [],
    myOvertimes: [],
    currentOvertime: {},
    overtimeTypes: [],
    currentOvertimeType: {},
    attendances: [],
    myAttendances: [],
    allUsers: [],
  }
}
